services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    networks:
      - dokploy-network
      - my-ipv6-network

networks:
  my-ipv6-network:
    external: true
  dokploy-network:
    external: true
